import { pgTable, text, serial, timestamp, integer, numeric, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// Auto-drafted by Trigger T3 when a tank's gallons drop below its refill threshold.
// Also usable as a manual purchase order entity.
export const purchaseOrdersTable = pgTable("purchase_orders", {
  id: serial("id").primaryKey(),
  poNumber: text("po_number"),
  // status: draft | submitted | acknowledged | received | cancelled
  status: text("status").notNull().default("draft"),
  // source: auto:tank_refill | auto:variance | manual
  source: text("source").notNull().default("manual"),

  vendorName: text("vendor_name"),
  vendorContact: text("vendor_contact"),
  purchaseLocationId: integer("purchase_location_id"),

  tankId: integer("tank_id"),                   // For auto-drafted tank-refill POs
  triggeredByReminderId: integer("triggered_by_reminder_id"),

  subtotal: numeric("subtotal", { precision: 12, scale: 2 }),
  tax: numeric("tax", { precision: 12, scale: 2 }),
  total: numeric("total", { precision: 12, scale: 2 }),
  expectedDeliveryAt: timestamp("expected_delivery_at", { withTimezone: true }),
  receivedAt: timestamp("received_at", { withTimezone: true }),
  notes: text("notes"),
  createdById: integer("created_by_id"),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const purchaseOrderLinesTable = pgTable("purchase_order_lines", {
  id: serial("id").primaryKey(),
  purchaseOrderId: integer("purchase_order_id").notNull(),
  materialId: integer("material_id"),
  description: text("description").notNull(),
  quantity: numeric("quantity", { precision: 10, scale: 2 }).notNull().default("1"),
  unitCost: numeric("unit_cost", { precision: 10, scale: 2 }),
  lineTotal: numeric("line_total", { precision: 12, scale: 2 }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertPurchaseOrderSchema = createInsertSchema(purchaseOrdersTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertPurchaseOrder = z.infer<typeof insertPurchaseOrderSchema>;
export type PurchaseOrder = typeof purchaseOrdersTable.$inferSelect;

export const insertPurchaseOrderLineSchema = createInsertSchema(purchaseOrderLinesTable).omit({ id: true, createdAt: true });
export type InsertPurchaseOrderLine = z.infer<typeof insertPurchaseOrderLineSchema>;
export type PurchaseOrderLine = typeof purchaseOrderLinesTable.$inferSelect;
